### ISSUE TITLE
app.js file - Routes collection should be in a designated file

### ISSUE THREAD

**Issue by AsafEini** [roystern92/TODO_LIST_MERN_CLIENT#1]
1) remove the routes from the app.js file and create a designated file to routes.
as the applications grows there will be more and more routes.
2) put all the routes paths in a in contants, for example :
instead of :

                <Switch>
                    <Route path="/my-day" component={MyDay}/>
                    <Route path="/my-lists" component={Loader}/>
                    <Route path="/profile" component={Profile}/>
                    <Route path="/test" exact component={MyDay}/>
                    <Route path="/logout" component={Logout}/>
                    <Redirect to="/my-day"/>
                </Switch>
do:

                <Switch>
                    <Route path=DAY_ROUTE component={MyDay}/>
                    <Route path= LIST_ROUTE component={Loader}/>
                    <Route path=PROFILE_ROUTE component={Profile}/>
                    <Route path=TEST_ROUTE exact component={MyDay}/>
                    <Route path=LOGOUT_ROUTE component={Logout}/>
                    <Redirect to=DAY_ROUTE/>
                </Switch>
reuse reuse reuse

3) why do: **let routes = null;** you can just **let routes;**  

4) on mapStateToProps you wrote : **isAuthenticated: state.auth.token !== null** instead you can just do **isAuthenticated: !!state.auth.token**

**Comment by roystern92** [comment]
thank you for the feedback.
