### ISSUE TITLE
AuthForm.js

### ISSUE THREAD

**Issue by AsafEini** [roystern92/TODO_LIST_MERN_CLIENT#2]
1) change to :

> 
createInputs = (formElementsArray) => {
>         let inputs = formElementsArray.map(formElement => {
>             const {
>                      id, 
>                     config: {
>                              value, 
>                              valid, 
>                             touched, 
>                             validation,
>                            elementConfig, 
>                            value}}} = formElement; 
>             return <Input
>                 label={id}
>                 key={id}
>                 value={value}
>                 invalid={!valid}
>                 touched={touched}
>                 shouldValidate={validation}
>                 elementConfig={elementConfig}
>                 value={value}
>                 changed={(event) => this.onInputChangeHandler(event, id)}
>             />
>         });
>         return inputs;
>     };

> 

2) AuthForm is too big and its not good lets discuss how can we break it even more

**Comment by roystern92** [comment]
Thanks.
